### ISSUE TITLE
Expose pending field for async functions

### ISSUE THREAD

**Issue by MolotovCherry** [blackbeam/named_pipe#12]
As it turns out, so far only internals know if an async read/write is finished or not. It would be useful if there was a way for callers to check whether the read/write is done or not without having to call .wait() on the Read/WriteHandle, that way they can continue their async work and poll later to see if it's ready. Having to to a blocking wait() on an async method just to be sure the data is done defeats the purpose doesn't it?

**Comment by blackbeam** [comment]
Hi, @cherryleafroad.
The `pending` field is not "reactive", so it won't tell you whether read/write is finished or not.

> It would be useful if there was a way for callers to check whether the read/write is done or not

You can achieve this explicitly specifying zero duration using `set_(read|write)_timeout`. `WaitForSingleObject` guarantees that it won't block if the timeout is zero. I believe it's possible to come up with a better API, but for now, I'd suggest you consider [miow implementation][1] for async use cases.

[1]: https://docs.rs/miow/0.3.6/miow/pipe/index.html

**Comment by MolotovCherry** [comment]
Thank you for your reply! 

I read a lot of your code and tried to understand it. So calling a `.wait()` with a timeout of 0 will return immediately, and if no data was read yet it may return having read 0 bytes, or return having read some bytes. Can I infer that if 0 bytes have been read, it isn't finished reading, and if bytes read > 0, the read is completely done and I can operate on the data?

**Comment by blackbeam** [comment]
> So calling a .wait() with a timeout of 0 will return immediately, and if no data was read yet it may return having read 0 bytes

I believe it'll return `Err(err)` where `err.kind() == std::io::ErrorKind::TimeOut` if read is not yet finished.
