### ISSUE TITLE
Segfault when connecting named pipe

### ISSUE THREAD

**Issue by alexcrichton** [blackbeam/named_pipe#3]
I believe that when executing overlapped operations on Windows a requirements is that the address of the `OVERLAPPED` passed in does not change, but I believe that [during pipe creation](https://github.com/blackbeam/named_pipe/blob/071a44d11897ee781e7c62df1a8ae455b9d7376a/src/lib.rs#L233) the overlapped passed in does indeed change addresses, which I think can cause segfaults.

**Comment by retep998** [comment]
The simple fix for this is to box the `OVERLAPPED` before passing the pointer to Windows and then keep it in that box until the operation is complete.

**Comment by blackbeam** [comment]
🤦‍♂️
